fix: fail build if go mod tidy dirties the repository
prevents `-dirty` versions on `debug.ReadBuildInfo()`

Signed-off-by: Carlos Alexandro Becker <caarlos0@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -61,8 +61,15 @@ jobs:
           go-version: ${{ inputs.go_version || inputs.go-version }}
           go-version-file: ${{ inputs.go-version-file }}
           cache: true
-      - name: Download Go modules
-        run: go mod download
+      - name: Tidy Go modules
+        run: go mod tidy
+        working-directory: ${{ inputs.working-directory }}
+      - run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Error: git status is not clean after go mod tidy"
+            git status
+            exit 1
+          fi
         working-directory: ${{ inputs.working-directory }}
       - name: Build
         run: go build ./...
